### ISSUE TITLE
Render the current weather conditions 

### ISSUE THREAD

**Issue by sarabenchinoun** [sarabenchinoun/weather-dashboard#3]
### Tasks

- [ ] The city name
- [ ] The date
- [ ] An icon representation of weather conditions
- [ ] The temperature
- [ ] The humidity
- [ ] The wind speed
